### ISSUE TITLE
404 for the release note on the F# Language

### ISSUE THREAD

**Issue by nodakai** [fsharp/fsharp-compiler-docs#1005]
Case 1:
![Screenshot 2024-09-17 at 00-49-42 About F# Compiler Guide](https://github.com/user-attachments/assets/5cec6188-99a5-43ab-ace9-fc79e559567a)
=> https://fsharp.github.io/fsharp-compiler-docs/release-notes/Language.md

Case 2:
![Screenshot 2024-09-17 at 00-55-46 F# Language F# Compiler Guide](https://github.com/user-attachments/assets/ea401136-5b63-4bd1-a065-66bf8c5429c4)

**Comment by nojaf** [comment]
For case 2 you would need to check what happens when you evaluate https://github.com/dotnet/fsharp/blob/main/docs/release-notes/Language.fsx

**Comment by nojaf** [comment]
Think https://github.com/dotnet/fsharp/pull/17750 will do the trick.

**Comment by nojaf** [comment]
Should be fixed now, https://fsharp.github.io/fsharp-compiler-docs/release-notes/Language.html

**Comment by nodakai** [comment]
confirmed, thanks!
