### ISSUE TITLE
FSI evaluator references fsiAux library

### ISSUE THREAD

**Issue by tpetricek** [fsharp/fsharp-compiler-docs#127]
When you let F# Formatting automatically evaluate your snippets and output the results, it uses `FsiEvaluationSession` [like this](https://github.com/tpetricek/FSharp.Formatting/blob/f0696978ac0f436b24d4287ee99effd9d02b3ba9/src/FSharp.Literate/Evaluator.fs#L83):

```
let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration(new InteractiveSettings())
let argv = Array.append [|"C:\\test.exe"; "--noninteractive"|] (defaultArg options [||])
let fsiSession = FsiEvaluationSession(fsiConfig, argv, inStream, outStream, errStream)
```

When I run this, the value `fsiConfig.UseFsiAux` is `true` and so the service tries to load `FSharp.Compiler.Interactive.dll`. This works fine when run from F# Interactive (which is how F# Formatting is used normally), but fails when called from stand-alone command line app. It ends up searching for the file in `defaultFSharpBinariesDir`, which is [initialized here as follows](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/fsi/fsi.fs#L2301):

```
let defaultFSharpBinariesDir = System.AppDomain.CurrentDomain.BaseDirectory
```

In F# Interactive, this returns the "Program Files" directory which happens to have `FSharp.Interactive.Service`, but in stand-alone command line app, this is the local directory and it fails...

**Comment by nosami** [comment]
The useFsiAuxLib flag doesn't seem to work.

I'm launching the Evaluation session like this

```
        let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration(Settings.fsi, false)

        let fsiSession = FsiEvaluationSession.Create(fsiConfig, argv, inStream, outStream, outStream, true)
```

Where `Settings.fsi` is my own object and I get the error `The namespace or module 'fsi' is not defined` whenever a script tries to access the `fsi` object. The only way I have been able to make it work is by directly referencing the Interactive.Settings.dll

**Comment by matthid** [comment]
@nosami I solved the same problem in the Yaaf.FSharp.Scripting library. You can either use the library directly or copy the workaround (https://github.com/matthid/Yaaf.FSharp.Scripting/blob/develop/src/source/Yaaf.FSharp.Scripting/YaafFSharpScripting.fs#L1111)

**Comment by nosami** [comment]
Hi @matthid - I found your library since posting, it's been very useful to look at the source, thanks!. 

I don't think I can use it as-is though. I'm building a replacement fsi window for Xamarin Studio, and I need access to the underlying FSharpCheckResults for things like completions.

**Comment by nosami** [comment]
Thing is, I don't even need my own fsi object, the one in FSharp.Compiler.Interactive.Settings.dll is fine. I was just trying to avoid having a direct reference to it.

**Comment by matthid** [comment]
@nosami Yes I tried to keep the surface as small as possible and extend as needed, if you have suggestions to improve please open an issue or PR :). Maybe we should allow to acess the underlying FSIEvaluationSession instance to get the real deal...
