### ISSUE TITLE
Broken links on docs homepage

### ISSUE THREAD

**Issue by 0101** [fsharp/fsharp-compiler-docs#970]
Links on [docs homepage](https://fsharp.github.io/fsharp-compiler-docs/) under **Documentation Topics** are broken. They point to e.g. 
- `https://fsharp.github.io/fsharp-compiler-docs/overview.md` 
instead of just 
- `https://fsharp.github.io/fsharp-compiler-docs/overview` 

It should _probably_ be fixed in https://github.com/fsprojects/FSharp.Formatting but we could also just remove the `.md` suffixes from the docs source. Which will probably work fine everywhere.

**Comment by baronfel** [comment]
I wonder if this has already been fixed in the FSharp.Formatting tool? I think we're quite behind in this repository at the moment.

**Comment by nojaf** [comment]
Nope, we put in `.html` in our Markdown files in the Fantomas repo to overcome this.
It still is a problem in `fsdocs`. Not sure if there already is an issue created for that.

**Comment by dsyme** [comment]
Should be fixed by https://github.com/fsprojects/FSharp.Formatting/pull/767

Problem seems to have been related to using relative input paths (which is normal) - the testing for FSharp.Formatting was only testing absolute input paths `--input <absolute-path>`

**Comment by nojaf** [comment]
This appears to be fixed.
