### ISSUE TITLE
Product-specific changelogs aren't rendered helpfully in the nav

### ISSUE THREAD

**Issue by baronfel** [fsharp/fsharp-compiler-docs#990]
![image](https://github.com/fsharp/fsharp-compiler-docs/assets/573979/84990d4f-4788-486c-892f-dca8ededaf8d)

These links point to:
* https://fsharp.github.io/fsharp-compiler-docs/release-notes/FSharp.Core/8.0.200.html
* https://fsharp.github.io/fsharp-compiler-docs/release-notes/FSharp.Compiler.Service/8.0.200.html
* https://fsharp.github.io/fsharp-compiler-docs/release-notes/Language/preview.html

respectively, but the product isn't represented in the nav in any way so it's confusing.

**Comment by nojaf** [comment]
These files do not contain frontmatter so what happens technically makes sense.
I'm trying to address this in https://github.com/dotnet/fsharp/pull/16377#issuecomment-1840925921
